### ISSUE TITLE
Reset service as void

### ISSUE THREAD

**Issue by JakubWienzek** [sligocki-lgbs/game-of-war#15]
https://github.com/s-ligocki/game-of-war/blob/d954ab22ca98390ce753ecb35284ad86140d85ed/game-of-war-rest/src/main/java/com/beleco/gameofwar/controller/GameController.java#L34

I'm not sure if this service should be 'void'. In front when user click "Reset" I will call a service and it will be best for me to get an answer that this operation is done. Without it it will be possible to try to get new game before I was deleted from the last one.

**Comment by s-ligocki** [comment]
Fully agree. Although you could check method success by reading http response code, I agree that returning void is a bad practice. 
Solved the problem with ResponseStatus object.

**Comment by JakubWienzek** [comment]
Yeah, it was already doing that but I thought that it's not enough. ;)
